/*
 * These are metadata resources (from /api/resources) which are known to support paging.
 * They should all also support fields declarations.  Only plural resource names are supported.
 * This list may be incomplete, and may require updating for new DHIS2 major versions
 */

export const normativeMetadataResources = [
    'programDataElements',
    'indicatorTypes',
    'programs',
    'optionGroups',
    'programRuleVariables',
    'reports',
    'users',
    'constants',
    'externalMapLayers',
    'analyticsTableHooks',
    'pushAnalysis',
    'oAuth2Clients',
    'validationRules',
    'reportTables',
    'userGroups',
    'sqlViews',
    'sections',
    'validationNotificationTemplates',
    'optionGroupSets',
    'organisationUnitGroupSets',
    'trackedEntityAttributes',
    'dashboardItems',
    'categoryCombos',
    'programSections',
    'trackedEntityTypes',
    'dataSetNotificationTemplates',
    'maps',
    'dataApprovalWorkflows',
    'programStages',
    'categoryOptionGroups',
    'relationshipTypes',
    'validationRuleGroups',
    'predictors',
    'dataSets',
    'options',
    'organisationUnitLevels',
    'dataEntryForms',
    'predictorGroups',
    'dataElementGroupSets',
    'programIndicatorGroups',
    'dataApprovalLevels',
    'organisationUnits',
    'programIndicators',
    'dataElements',
    'mapViews',
    'categories',
    'categoryOptionCombos',
    'documents',
    'indicators',
    'optionSets',
    'interpretations',
    'programRuleActions',
    'dataElementGroups',
    'attributes',
    'validationResults',
    'categoryOptions',
    'indicatorGroupSets',
    'messageConversations',
    'dashboards',
    'programNotificationTemplates',
    'programStageSections',
    'legendSets',
    'organisationUnitGroups',
    'visualizations',
    'indicatorGroups',
    'programTrackedEntityAttributeGroups',
    'programRules',
    'categoryOptionGroupSets',
    'userRoles',
    'eventFilters',
    'eventReports',
    'eventCharts',
    'smsCommands',
    'jobConfigurations',
    'minMaxDataElements',
    'charts',
    'dataElementOperands',

    // These exist and appear to accept field declarations, but have abnormal behavior when it comes to viewing collections and paging results
    'trackedEntityInstance',
    'relationships',
]

// Including non-normative resources listed under /api/resources for future follow-up
export const nonNormativeMetadataResources = [
    'trackedEntityAttributeValues',
    'programInstances',
    'expressions',
    'programStageInstances',
    'externalFileResources',
    'icons',
    'fileResources',
    'metadataVersions',
    'dataStores', // This doesn't exist, but is listed as the plural of 'dataStore' in /api/resources

    // Known but missing from /api/resources
    'userDataStore',
    'apps',
]
