connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://${DB_HOSTNAME:-db}/${DB_NAME:-dhis2}
connection.username = ${DB_USERNAME:-dhis}
connection.password = ${DB_PASSWORD:-dhis}
