name: 'dhis2: verify (commits)'

on:
    push:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    lint-pr-title:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'yarn'
            - run: yarn add -W @commitlint/config-conventional
            - id: commitlint
              run: |
                  curl https://raw.githubusercontent.com/dhis2/cli-style/refs/heads/master/config/commitlint.config.js -o commitlint.config.js
            - uses: JulienKode/pull-request-name-linter-action@v20.1.0 # uses config from commitlint.config.js by default

    lint-commits:
        runs-on: ubuntu-latest
        # if: ${{ !contains(github.event.pull_request.title, '[skip release]') }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'yarn'
            - run: yarn add -W @commitlint/config-conventional@13
            - id: commitlint
              run: |
                  curl https://raw.githubusercontent.com/dhis2/cli-style/refs/heads/master/config/commitlint.config.js -o commitlint.config.js
                  echo ::set-output name=config_path::commitlint.config.js
            - run: echo ${{ steps.commitlint.outputs.config_path }}
            - run: cat ${{ steps.commitlint.outputs.config_path }}
            - uses: wagoid/commitlint-github-action@v4
              with:
                  configFile: ${{ steps.commitlint.outputs.config_path }}
